// flow-typed signature: 5f445729fcf5c84c99f888c706a22990
// flow-typed version: <<STUB>>/eslint-plugin-react_v^3.16.1/flow_v0.45.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-plugin-react'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-plugin-react' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-plugin-react/lib/rules/display-name' {
  declare module.exports: any;
}

declare module 'eslint-plugin-react/lib/rules/forbid-prop-types' {
  declare module.exports: any;
}

declare module 'eslint-plugin-react/lib/rules/jsx-boolean-value' {
  declare module.exports: any;
}

declare module 'eslint-plugin-react/lib/rules/jsx-closing-bracket-location' {
  declare module.exports: any;
}

declare module 'eslint-plugin-react/lib/rules/jsx-curly-spacing' {
  declare module.exports: any;
}

declare module 'eslint-plugin-react/lib/rules/jsx-equals-spacing' {
  declare module.exports: any;
}

declare module 'eslint-plugin-react/lib/rules/jsx-handler-names' {
  declare module.exports: any;
}

declare module 'eslint-plugin-react/lib/rules/jsx-indent-props' {
  declare module.exports: any;
}

declare module 'eslint-plugin-react/lib/rules/jsx-indent' {
  declare module.exports: any;
}

declare module 'eslint-plugin-react/lib/rules/jsx-key' {
  declare module.exports: any;
}

declare module 'eslint-plugin-react/lib/rules/jsx-max-props-per-line' {
  declare module.exports: any;
}

declare module 'eslint-plugin-react/lib/rules/jsx-no-bind' {
  declare module.exports: any;
}

declare module 'eslint-plugin-react/lib/rules/jsx-no-duplicate-props' {
  declare module.exports: any;
}

declare module 'eslint-plugin-react/lib/rules/jsx-no-literals' {
  declare module.exports: any;
}

declare module 'eslint-plugin-react/lib/rules/jsx-no-undef' {
  declare module.exports: any;
}

declare module 'eslint-plugin-react/lib/rules/jsx-pascal-case' {
  declare module.exports: any;
}

declare module 'eslint-plugin-react/lib/rules/jsx-quotes' {
  declare module.exports: any;
}

declare module 'eslint-plugin-react/lib/rules/jsx-sort-prop-types' {
  declare module.exports: any;
}

declare module 'eslint-plugin-react/lib/rules/jsx-sort-props' {
  declare module.exports: any;
}

declare module 'eslint-plugin-react/lib/rules/jsx-uses-react' {
  declare module.exports: any;
}

declare module 'eslint-plugin-react/lib/rules/jsx-uses-vars' {
  declare module.exports: any;
}

declare module 'eslint-plugin-react/lib/rules/no-danger' {
  declare module.exports: any;
}

declare module 'eslint-plugin-react/lib/rules/no-deprecated' {
  declare module.exports: any;
}

declare module 'eslint-plugin-react/lib/rules/no-did-mount-set-state' {
  declare module.exports: any;
}

declare module 'eslint-plugin-react/lib/rules/no-did-update-set-state' {
  declare module.exports: any;
}

declare module 'eslint-plugin-react/lib/rules/no-direct-mutation-state' {
  declare module.exports: any;
}

declare module 'eslint-plugin-react/lib/rules/no-is-mounted' {
  declare module.exports: any;
}

declare module 'eslint-plugin-react/lib/rules/no-multi-comp' {
  declare module.exports: any;
}

declare module 'eslint-plugin-react/lib/rules/no-set-state' {
  declare module.exports: any;
}

declare module 'eslint-plugin-react/lib/rules/no-string-refs' {
  declare module.exports: any;
}

declare module 'eslint-plugin-react/lib/rules/no-unknown-property' {
  declare module.exports: any;
}

declare module 'eslint-plugin-react/lib/rules/prefer-es6-class' {
  declare module.exports: any;
}

declare module 'eslint-plugin-react/lib/rules/prop-types' {
  declare module.exports: any;
}

declare module 'eslint-plugin-react/lib/rules/react-in-jsx-scope' {
  declare module.exports: any;
}

declare module 'eslint-plugin-react/lib/rules/require-extension' {
  declare module.exports: any;
}

declare module 'eslint-plugin-react/lib/rules/self-closing-comp' {
  declare module.exports: any;
}

declare module 'eslint-plugin-react/lib/rules/sort-comp' {
  declare module.exports: any;
}

declare module 'eslint-plugin-react/lib/rules/wrap-multilines' {
  declare module.exports: any;
}

declare module 'eslint-plugin-react/lib/util/Components' {
  declare module.exports: any;
}

declare module 'eslint-plugin-react/lib/util/pragma' {
  declare module.exports: any;
}

declare module 'eslint-plugin-react/lib/util/variable' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-plugin-react/index' {
  declare module.exports: $Exports<'eslint-plugin-react'>;
}
declare module 'eslint-plugin-react/index.js' {
  declare module.exports: $Exports<'eslint-plugin-react'>;
}
declare module 'eslint-plugin-react/lib/rules/display-name.js' {
  declare module.exports: $Exports<'eslint-plugin-react/lib/rules/display-name'>;
}
declare module 'eslint-plugin-react/lib/rules/forbid-prop-types.js' {
  declare module.exports: $Exports<'eslint-plugin-react/lib/rules/forbid-prop-types'>;
}
declare module 'eslint-plugin-react/lib/rules/jsx-boolean-value.js' {
  declare module.exports: $Exports<'eslint-plugin-react/lib/rules/jsx-boolean-value'>;
}
declare module 'eslint-plugin-react/lib/rules/jsx-closing-bracket-location.js' {
  declare module.exports: $Exports<'eslint-plugin-react/lib/rules/jsx-closing-bracket-location'>;
}
declare module 'eslint-plugin-react/lib/rules/jsx-curly-spacing.js' {
  declare module.exports: $Exports<'eslint-plugin-react/lib/rules/jsx-curly-spacing'>;
}
declare module 'eslint-plugin-react/lib/rules/jsx-equals-spacing.js' {
  declare module.exports: $Exports<'eslint-plugin-react/lib/rules/jsx-equals-spacing'>;
}
declare module 'eslint-plugin-react/lib/rules/jsx-handler-names.js' {
  declare module.exports: $Exports<'eslint-plugin-react/lib/rules/jsx-handler-names'>;
}
declare module 'eslint-plugin-react/lib/rules/jsx-indent-props.js' {
  declare module.exports: $Exports<'eslint-plugin-react/lib/rules/jsx-indent-props'>;
}
declare module 'eslint-plugin-react/lib/rules/jsx-indent.js' {
  declare module.exports: $Exports<'eslint-plugin-react/lib/rules/jsx-indent'>;
}
declare module 'eslint-plugin-react/lib/rules/jsx-key.js' {
  declare module.exports: $Exports<'eslint-plugin-react/lib/rules/jsx-key'>;
}
declare module 'eslint-plugin-react/lib/rules/jsx-max-props-per-line.js' {
  declare module.exports: $Exports<'eslint-plugin-react/lib/rules/jsx-max-props-per-line'>;
}
declare module 'eslint-plugin-react/lib/rules/jsx-no-bind.js' {
  declare module.exports: $Exports<'eslint-plugin-react/lib/rules/jsx-no-bind'>;
}
declare module 'eslint-plugin-react/lib/rules/jsx-no-duplicate-props.js' {
  declare module.exports: $Exports<'eslint-plugin-react/lib/rules/jsx-no-duplicate-props'>;
}
declare module 'eslint-plugin-react/lib/rules/jsx-no-literals.js' {
  declare module.exports: $Exports<'eslint-plugin-react/lib/rules/jsx-no-literals'>;
}
declare module 'eslint-plugin-react/lib/rules/jsx-no-undef.js' {
  declare module.exports: $Exports<'eslint-plugin-react/lib/rules/jsx-no-undef'>;
}
declare module 'eslint-plugin-react/lib/rules/jsx-pascal-case.js' {
  declare module.exports: $Exports<'eslint-plugin-react/lib/rules/jsx-pascal-case'>;
}
declare module 'eslint-plugin-react/lib/rules/jsx-quotes.js' {
  declare module.exports: $Exports<'eslint-plugin-react/lib/rules/jsx-quotes'>;
}
declare module 'eslint-plugin-react/lib/rules/jsx-sort-prop-types.js' {
  declare module.exports: $Exports<'eslint-plugin-react/lib/rules/jsx-sort-prop-types'>;
}
declare module 'eslint-plugin-react/lib/rules/jsx-sort-props.js' {
  declare module.exports: $Exports<'eslint-plugin-react/lib/rules/jsx-sort-props'>;
}
declare module 'eslint-plugin-react/lib/rules/jsx-uses-react.js' {
  declare module.exports: $Exports<'eslint-plugin-react/lib/rules/jsx-uses-react'>;
}
declare module 'eslint-plugin-react/lib/rules/jsx-uses-vars.js' {
  declare module.exports: $Exports<'eslint-plugin-react/lib/rules/jsx-uses-vars'>;
}
declare module 'eslint-plugin-react/lib/rules/no-danger.js' {
  declare module.exports: $Exports<'eslint-plugin-react/lib/rules/no-danger'>;
}
declare module 'eslint-plugin-react/lib/rules/no-deprecated.js' {
  declare module.exports: $Exports<'eslint-plugin-react/lib/rules/no-deprecated'>;
}
declare module 'eslint-plugin-react/lib/rules/no-did-mount-set-state.js' {
  declare module.exports: $Exports<'eslint-plugin-react/lib/rules/no-did-mount-set-state'>;
}
declare module 'eslint-plugin-react/lib/rules/no-did-update-set-state.js' {
  declare module.exports: $Exports<'eslint-plugin-react/lib/rules/no-did-update-set-state'>;
}
declare module 'eslint-plugin-react/lib/rules/no-direct-mutation-state.js' {
  declare module.exports: $Exports<'eslint-plugin-react/lib/rules/no-direct-mutation-state'>;
}
declare module 'eslint-plugin-react/lib/rules/no-is-mounted.js' {
  declare module.exports: $Exports<'eslint-plugin-react/lib/rules/no-is-mounted'>;
}
declare module 'eslint-plugin-react/lib/rules/no-multi-comp.js' {
  declare module.exports: $Exports<'eslint-plugin-react/lib/rules/no-multi-comp'>;
}
declare module 'eslint-plugin-react/lib/rules/no-set-state.js' {
  declare module.exports: $Exports<'eslint-plugin-react/lib/rules/no-set-state'>;
}
declare module 'eslint-plugin-react/lib/rules/no-string-refs.js' {
  declare module.exports: $Exports<'eslint-plugin-react/lib/rules/no-string-refs'>;
}
declare module 'eslint-plugin-react/lib/rules/no-unknown-property.js' {
  declare module.exports: $Exports<'eslint-plugin-react/lib/rules/no-unknown-property'>;
}
declare module 'eslint-plugin-react/lib/rules/prefer-es6-class.js' {
  declare module.exports: $Exports<'eslint-plugin-react/lib/rules/prefer-es6-class'>;
}
declare module 'eslint-plugin-react/lib/rules/prop-types.js' {
  declare module.exports: $Exports<'eslint-plugin-react/lib/rules/prop-types'>;
}
declare module 'eslint-plugin-react/lib/rules/react-in-jsx-scope.js' {
  declare module.exports: $Exports<'eslint-plugin-react/lib/rules/react-in-jsx-scope'>;
}
declare module 'eslint-plugin-react/lib/rules/require-extension.js' {
  declare module.exports: $Exports<'eslint-plugin-react/lib/rules/require-extension'>;
}
declare module 'eslint-plugin-react/lib/rules/self-closing-comp.js' {
  declare module.exports: $Exports<'eslint-plugin-react/lib/rules/self-closing-comp'>;
}
declare module 'eslint-plugin-react/lib/rules/sort-comp.js' {
  declare module.exports: $Exports<'eslint-plugin-react/lib/rules/sort-comp'>;
}
declare module 'eslint-plugin-react/lib/rules/wrap-multilines.js' {
  declare module.exports: $Exports<'eslint-plugin-react/lib/rules/wrap-multilines'>;
}
declare module 'eslint-plugin-react/lib/util/Components.js' {
  declare module.exports: $Exports<'eslint-plugin-react/lib/util/Components'>;
}
declare module 'eslint-plugin-react/lib/util/pragma.js' {
  declare module.exports: $Exports<'eslint-plugin-react/lib/util/pragma'>;
}
declare module 'eslint-plugin-react/lib/util/variable.js' {
  declare module.exports: $Exports<'eslint-plugin-react/lib/util/variable'>;
}
