// flow-typed signature: f2ae2630a09c668803655a4b82b104be
// flow-typed version: <<STUB>>/gh-pages_v^2.0.1/flow_v0.111.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gh-pages'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gh-pages' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'gh-pages/bin/gh-pages-clean' {
  declare module.exports: any;
}

declare module 'gh-pages/bin/gh-pages' {
  declare module.exports: any;
}

declare module 'gh-pages/lib/git' {
  declare module.exports: any;
}

declare module 'gh-pages/lib/index' {
  declare module.exports: any;
}

declare module 'gh-pages/lib/util' {
  declare module.exports: any;
}

declare module 'gh-pages/plugin' {
  declare module.exports: any;
}

// Filename aliases
declare module 'gh-pages/bin/gh-pages-clean.js' {
  declare module.exports: $Exports<'gh-pages/bin/gh-pages-clean'>;
}
declare module 'gh-pages/bin/gh-pages.js' {
  declare module.exports: $Exports<'gh-pages/bin/gh-pages'>;
}
declare module 'gh-pages/lib/git.js' {
  declare module.exports: $Exports<'gh-pages/lib/git'>;
}
declare module 'gh-pages/lib/index.js' {
  declare module.exports: $Exports<'gh-pages/lib/index'>;
}
declare module 'gh-pages/lib/util.js' {
  declare module.exports: $Exports<'gh-pages/lib/util'>;
}
declare module 'gh-pages/plugin.js' {
  declare module.exports: $Exports<'gh-pages/plugin'>;
}
