// flow-typed signature: ba8625f8602b30b059eacb13171ab937
// flow-typed version: <<STUB>>/loose-envify_v^1.4.0/flow_v0.111.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   'loose-envify'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'loose-envify' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'loose-envify/cli' {
  declare module.exports: any;
}

declare module 'loose-envify/custom' {
  declare module.exports: any;
}

declare module 'loose-envify/loose-envify' {
  declare module.exports: any;
}

declare module 'loose-envify/replace' {
  declare module.exports: any;
}

// Filename aliases
declare module 'loose-envify/cli.js' {
  declare module.exports: $Exports<'loose-envify/cli'>;
}
declare module 'loose-envify/custom.js' {
  declare module.exports: $Exports<'loose-envify/custom'>;
}
declare module 'loose-envify/index' {
  declare module.exports: $Exports<'loose-envify'>;
}
declare module 'loose-envify/index.js' {
  declare module.exports: $Exports<'loose-envify'>;
}
declare module 'loose-envify/loose-envify.js' {
  declare module.exports: $Exports<'loose-envify/loose-envify'>;
}
declare module 'loose-envify/replace.js' {
  declare module.exports: $Exports<'loose-envify/replace'>;
}
