// flow-typed signature: 7140e6f3fd6d62574753e155236e9005
// flow-typed version: <<STUB>>/webpack-cli_v^3.1.2/flow_v0.111.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   'webpack-cli'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'webpack-cli' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'webpack-cli/bin/cli' {
  declare module.exports: any;
}

declare module 'webpack-cli/bin/config/config-yargs' {
  declare module.exports: any;
}

declare module 'webpack-cli/bin/utils/constants' {
  declare module.exports: any;
}

declare module 'webpack-cli/bin/utils/convert-argv' {
  declare module.exports: any;
}

declare module 'webpack-cli/bin/utils/errorHelpers' {
  declare module.exports: any;
}

declare module 'webpack-cli/bin/utils/prepareOptions' {
  declare module.exports: any;
}

declare module 'webpack-cli/bin/utils/prompt-command' {
  declare module.exports: any;
}

declare module 'webpack-cli/bin/utils/validate-options' {
  declare module.exports: any;
}

// Filename aliases
declare module 'webpack-cli/bin/cli.js' {
  declare module.exports: $Exports<'webpack-cli/bin/cli'>;
}
declare module 'webpack-cli/bin/config/config-yargs.js' {
  declare module.exports: $Exports<'webpack-cli/bin/config/config-yargs'>;
}
declare module 'webpack-cli/bin/utils/constants.js' {
  declare module.exports: $Exports<'webpack-cli/bin/utils/constants'>;
}
declare module 'webpack-cli/bin/utils/convert-argv.js' {
  declare module.exports: $Exports<'webpack-cli/bin/utils/convert-argv'>;
}
declare module 'webpack-cli/bin/utils/errorHelpers.js' {
  declare module.exports: $Exports<'webpack-cli/bin/utils/errorHelpers'>;
}
declare module 'webpack-cli/bin/utils/prepareOptions.js' {
  declare module.exports: $Exports<'webpack-cli/bin/utils/prepareOptions'>;
}
declare module 'webpack-cli/bin/utils/prompt-command.js' {
  declare module.exports: $Exports<'webpack-cli/bin/utils/prompt-command'>;
}
declare module 'webpack-cli/bin/utils/validate-options.js' {
  declare module.exports: $Exports<'webpack-cli/bin/utils/validate-options'>;
}
